# Puerto para el microservice-config
server:
  port: 8888

spring:
  application:
    name: microservice-config-server
  profiles:
    active: native # Perfil por defecto con el que trabaja Spring Boot
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations # Ruta donde se encuentran las configuraciones de todos nuestros microservices

