# Puerto para el microservice-course
server:
  port: 9090

spring:
  application:
    name: microservice-course
  datasource:
    url: jdbc:mysql://localhost:3306/db_courses?serverTimezone=America/Lima&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    # url: jdbc:postgresql://localhost:5432/db_courses
    # driver-class-name: org.postgresql.Driver
    # username: postgres
    # password: 150919
    username: root
    password: mysql
  jpa:
    hibernate:
      ddl-auto: create
    # database: postgresql
    # database-platform: org.hibernate.dialect.PostgreSQLDialect

# Configuracion para que el microservice-course se registre automaticamente en eureka
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      default-zone: http://localhost:8761/eureka