# La identacion es de 2 espacios en blanco
spring:
  application:
    name: microservice-eureka

# Puerto comun para Eureka Server
server:
  port: 8761

# Configuracion del servidor
# Por defecto eureka se registra asi mismo dentro del servidor, por lo tanto al colocar register-with-eureka: false, le decimos que no lo haga
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    server-url:
      defaultZone: http://localhost:${server.port}/eureka/
