# Puerto para el microservice-student
server:
  port: 8090

spring:
  application:
    name: microservice-student
  datasource:
    url: jdbc:mysql://localhost:3306/db_students?serverTimezone=America/Lima&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mysql
  jpa:
    hibernate:
      ddl-auto: create

# Configuracion para que el microservice-student se registre automaticamente en eureka
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
