spring:
  application:
    name: microservice-gateway
  config:
    import: optional:configserver:http://localhost:8888 # Esta configuracion de URL es temporal, hasta que configuremos el Microservicio de Config Server